# Generated by Django 5.1.6 on 2025-02-20 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicao',
            old_name='valor',
            new_name='distancia',
        ),
    ]
